name: CI

on:
  push:
    branches:
      - main
      - "clase/**"
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm test

      - name: Production build
        run: npm run build
